In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)



[1 2 3 4]


In [4]:
import time
a=np.random.rand(10000000)
b=np.random.rand(10000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()

print("vectorized version: "+str(1000*(toc-tic))+"ms")
print(str(a),len(a))
print(str(b),len(b))
print(str(c))

vectorized version: 5.774021148681641ms
[0.37584499 0.26876763 0.26937002 ... 0.42050922 0.7372869  0.05742288] 10000000
[0.80591978 0.8020101  0.03615703 ... 0.99390115 0.07240472 0.47795807] 10000000
2499591.827870168


In [5]:
u=np.exp(a)
v=np.log(a)
w=np.abs(a)
print(str(u),len(u))
print(str(v),len(v))
print(str(w),len(w))



[1.45622139 1.30835109 1.30913946 ... 1.52273676 2.09025674 1.05910359] 10000000
[-0.97857847 -1.31390808 -1.3116693  ... -0.86628888 -0.30477818
 -2.85731237] 10000000
[0.37584499 0.26876763 0.26937002 ... 0.42050922 0.7372869  0.05742288] 10000000


In [8]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)

c = a*b
print (c)

[[ 0.01554034 -0.00548963  0.0259657 ]
 [-0.37402753 -0.00221909  0.27642263]
 [ 0.00772533  0.02180713  0.00913073]]
